import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import WhatsAppButton from "@/components/WhatsAppButton";
import FacebookPixel from "@/components/FacebookPixel";
import GoogleTag from "@/components/GoogleTag";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    default: "EasyDev - Soluções Digitais",
    template: "%s | EasyDev",
  },
  description:
    "Transformando ideias em soluções digitais inovadoras. Especialistas em desenvolvimento de software e consultoria em TI.",
  keywords: [
    "EasyDev Soluções Digitais",
    "EasyDev Ibirité",
    "EasyDev desenvolvimento de software",
    "EasyDev consultoria em TI",
    "EasyDev soluções digitais",
    "EasyDev desenvolvimento web",
    "EasyDev aplicativos",
    "EasyDev sistemas",
    "EasyDev tecnologia",
    "EasyDev transformação digital",
    "EasyDev desenvolvimento ágil",
    "EasyDev consultoria tecnológica",
    "EasyDev sistemas personalizados",
    "EasyDev aplicações web",
    "EasyDev desenvolvimento mobile",
    "EasyDev soluções empresariais",
    "EasyDev inovação digital",
    "EasyDev automação de processos",
    "EasyDev desenvolvimento de sistemas",
    "EasyDev consultoria em desenvolvimento",
    "EasyDev desenvolvimento de aplicativos",
    "EasyDev soluções em TI",
    "EasyDev desenvolvimento de sites",
    "EasyDev programação",
    "EasyDev software sob medida",
    "EasyDev sistemas web",
    "EasyDev aplicativos mobile",
    "EasyDev desenvolvimento de software em Ibirité",
    "EasyDev consultoria em tecnologia",
    "EasyDev soluções tecnológicas",
    "EasyDev desenvolvimento de software personalizado",
    "EasyDev criação de sites",
    "EasyDev desenvolvimento de aplicativos mobile",
    "EasyDev sistemas empresariais",
    "EasyDev automação de negócios",
    "EasyDev desenvolvimento de software ágil",
    "EasyDev consultoria em desenvolvimento de software",
    "EasyDev soluções digitais para empresas",
    "EasyDev desenvolvimento de software web",
    "EasyDev criação de aplicativos",
    "EasyDev desenvolvimento fullstack",
    "EasyDev frontend",
    "EasyDev backend",
    "EasyDev API",
    "EasyDev cloud computing",
    "EasyDev devops",
    "EasyDev segurança da informação",
    "EasyDev UX/UI design",
    "EasyDev testes automatizados",
    "EasyDev integração de sistemas",
    "EasyDev migração de dados",
    "EasyDev análise de requisitos",
    "EasyDev gestão de projetos",
    "EasyDev metodologias ágeis",
    "EasyDev scrum",
    "EasyDev kanban",
    "EasyDev MVP",
    "EasyDev prototipação",
    "EasyDev design thinking",
    "EasyDev business intelligence",
    "EasyDev análise de dados",
    "EasyDev machine learning",
    "EasyDev inteligência artificial",
    "EasyDev IoT",
    "EasyDev blockchain",
    "EasyDev realidade aumentada",
    "EasyDev realidade virtual",
    "EasyDev aplicativos híbridos",
    "EasyDev PWA",
    "EasyDev SEO",
    "EasyDev performance web",
    "EasyDev acessibilidade digital",
    "EasyDev compliance",
    "EasyDev LGPD",
    "EasyDev cybersecurity",
    "EasyDev backup e recuperação",
    "EasyDev monitoramento de sistemas",
    "EasyDev manutenção preventiva",
    "EasyDev suporte técnico",
    "EasyDev treinamento de equipes",
    "EasyDev documentação técnica",
    "EasyDev versionamento de código",
    "EasyDev integração contínua",
    "EasyDev entrega contínua",
    "EasyDev microserviços",
    "EasyDev arquitetura de software",
    "EasyDev clean code",
    "EasyDev design patterns",
    "EasyDev refatoração",
    "EasyDev otimização de código",
    "EasyDev performance de aplicações",
    "EasyDev escalabilidade",
    "EasyDev resiliência",
    "EasyDev monitoramento de performance",
    "EasyDev análise de métricas",
    "EasyDev relatórios de desempenho",
    "EasyDev gestão de mudanças",
    "EasyDev gestão de riscos",
    "EasyDev qualidade de software",
    "EasyDev testes de qualidade",
    "EasyDev garantia de qualidade",
    "EasyDev auditoria de sistemas",
    "EasyDev compliance tecnológico",
    "EasyDev governança de TI",
    "EasyDev gestão de ativos",
    "EasyDev gestão de serviços",
    "EasyDev ITIL",
    "EasyDev COBIT",
    "EasyDev ISO 27001",
    "EasyDev ISO 9001",
    "EasyDev certificações de segurança",
    "EasyDev treinamentos em TI",
    "EasyDev workshops técnicos",
    "EasyDev mentoria em desenvolvimento",
    "EasyDev consultoria estratégica",
    "EasyDev planejamento tecnológico",
    "EasyDev roadmap digital",
    "EasyDev transformação organizacional",
    "EasyDev digitalização de processos",
    "EasyDev automação de rotinas",
    "EasyDev workflow digital",
    "EasyDev gestão documental",
    "EasyDev gestão de conhecimento",
    "EasyDev colaboração digital",
    "EasyDev comunicação empresarial",
    "EasyDev ferramentas de produtividade",
    "EasyDev soluções em nuvem",
    "EasyDev infraestrutura como serviço",
    "EasyDev plataforma como serviço",
    "EasyDev software como serviço",
    "EasyDev virtualização",
    "EasyDev containers",
    "EasyDev kubernetes",
    "EasyDev docker",
    "EasyDev ansible",
    "EasyDev terraform",
    "EasyDev jenkins",
    "EasyDev gitlab",
    "EasyDev github",
    "EasyDev bitbucket",
    "EasyDev jira",
    "EasyDev confluence",
    "EasyDev slack",
    "EasyDev microsoft teams",
    "EasyDev zoom",
    "EasyDev trello",
    "EasyDev asana",
    "EasyDev monday",
    "EasyDev notion",
    "EasyDev figma",
    "EasyDev adobe xd",
    "EasyDev sketch",
    "EasyDev invision",
    "EasyDev zeplin",
    "EasyDev postman",
    "EasyDev swagger",
    "EasyDev graphql",
    "EasyDev rest api",
    "EasyDev soap",
    "EasyDev webservices",
    "EasyDev middleware",
    "EasyDev enterprise service bus",
    "EasyDev message queue",
    "EasyDev event streaming",
    "EasyDev kafka",
    "EasyDev rabbitmq",
    "EasyDev redis",
    "EasyDev mongodb",
    "EasyDev postgresql",
    "EasyDev mysql",
    "EasyDev oracle",
    "EasyDev sql server",
    "EasyDev nosql",
    "EasyDev big data",
    "EasyDev data warehouse",
    "EasyDev data lake",
    "EasyDev data mining",
    "EasyDev business analytics",
    "EasyDev data visualization",
    "EasyDev power bi",
    "EasyDev tableau",
    "EasyDev qlik",
    "EasyDev sap",
    "EasyDev salesforce",
    "EasyDev dynamics 365",
    "EasyDev oracle erp",
    "EasyDev sap erp",
    "EasyDev microsoft erp",
    "EasyDev sistema de gestão",
    "EasyDev crm",
    "EasyDev erp",
    "EasyDev wms",
    "EasyDev tms",
    "EasyDev hrms",
    "EasyDev scm",
    "EasyDev plm",
    "EasyDev mes",
    "EasyDev cms",
    "EasyDev lms",
    "EasyDev ecommerce",
    "EasyDev marketplace",
    "EasyDev omnichannel",
    "EasyDev digital marketing",
    "EasyDev social media",
    "EasyDev content marketing",
    "EasyDev inbound marketing",
    "EasyDev outbound marketing",
    "EasyDev email marketing",
    "EasyDev seo marketing",
    "EasyDev sem marketing",
    "EasyDev smm marketing",
    "EasyDev analytics marketing",
    "EasyDev growth hacking",
    "EasyDev conversion rate",
    "EasyDev landing pages",
    "EasyDev sales funnel",
    "EasyDev lead generation",
    "EasyDev customer success",
    "EasyDev customer experience",
    "EasyDev user experience",
    "EasyDev customer journey",
    "EasyDev design system",
    "EasyDev design tokens",
    "EasyDev atomic design",
    "EasyDev responsive design",
    "EasyDev mobile first",
    "EasyDev progressive enhancement",
    "EasyDev graceful degradation",
    "EasyDev cross browser",
    "EasyDev cross platform",
    "EasyDev cross device",
    "EasyDev responsive images",
    "EasyDev lazy loading",
    "EasyDev code splitting",
    "EasyDev tree shaking",
    "EasyDev bundle optimization",
    "EasyDev caching strategies",
    "EasyDev cdn",
    "EasyDev edge computing",
    "EasyDev serverless",
    "EasyDev lambda functions",
    "EasyDev api gateway",
    "EasyDev load balancing",
    "EasyDev auto scaling",
    "EasyDev disaster recovery",
    "EasyDev high availability",
    "EasyDev fault tolerance",
    "EasyDev redundancy",
    "EasyDev backup strategy",
    "EasyDev recovery strategy",
    "EasyDev business continuity",
    "EasyDev incident management",
    "EasyDev problem management",
    "EasyDev change management",
    "EasyDev release management",
    "EasyDev configuration management",
    "EasyDev asset management",
    "EasyDev capacity management",
    "EasyDev availability management",
    "EasyDev service level management",
    "EasyDev financial management",
    "EasyDev vendor management",
    "desenvolvimento de software",
    "consultoria em TI",
    "soluções digitais",
    "desenvolvimento web",
    "aplicativos",
    "sistemas",
    "tecnologia",
    "transformação digital",
    "EasyDev",
    "Ibirité",
    "desenvolvimento ágil",
    "consultoria tecnológica",
    "sistemas personalizados",
    "aplicações web",
    "desenvolvimento mobile",
    "soluções empresariais",
    "inovação digital",
    "automação de processos",
    "desenvolvimento de sistemas",
    "consultoria em desenvolvimento",
    "desenvolvimento de aplicativos",
    "soluções em TI",
    "desenvolvimento de sites",
    "programação",
    "software sob medida",
    "sistemas web",
    "aplicativos mobile",
    "desenvolvimento de software em Ibirité",
    "consultoria em tecnologia",
    "soluções tecnológicas",
    "desenvolvimento de software personalizado",
    "criação de sites",
    "desenvolvimento de aplicativos mobile",
    "sistemas empresariais",
    "automação de negócios",
    "desenvolvimento de software ágil",
    "consultoria em desenvolvimento de software",
    "soluções digitais para empresas",
    "desenvolvimento de software web",
    "criação de aplicativos",
    "desenvolvimento fullstack",
    "frontend",
    "backend",
    "API",
    "cloud computing",
    "devops",
    "segurança da informação",
    "UX/UI design",
    "testes automatizados",
    "integração de sistemas",
    "migração de dados",
    "análise de requisitos",
    "gestão de projetos",
    "metodologias ágeis",
    "scrum",
    "kanban",
    "MVP",
    "prototipação",
    "design thinking",
    "business intelligence",
    "análise de dados",
    "machine learning",
    "inteligência artificial",
    "IoT",
    "blockchain",
    "realidade aumentada",
    "realidade virtual",
    "aplicativos híbridos",
    "PWA",
    "SEO",
    "performance web",
    "acessibilidade digital",
    "compliance",
    "LGPD",
    "cybersecurity",
    "backup e recuperação",
    "monitoramento de sistemas",
    "manutenção preventiva",
    "suporte técnico",
    "treinamento de equipes",
    "documentação técnica",
    "versionamento de código",
    "integração contínua",
    "entrega contínua",
    "microserviços",
    "arquitetura de software",
    "clean code",
    "design patterns",
    "refatoração",
    "otimização de código",
    "performance de aplicações",
    "escalabilidade",
    "resiliência",
    "monitoramento de performance",
    "análise de métricas",
    "relatórios de desempenho",
    "gestão de mudanças",
    "gestão de riscos",
    "qualidade de software",
    "testes de qualidade",
    "garantia de qualidade",
    "auditoria de sistemas",
    "compliance tecnológico",
    "governança de TI",
    "gestão de ativos",
    "gestão de serviços",
    "ITIL",
    "COBIT",
    "ISO 27001",
    "ISO 9001",
    "certificações de segurança",
    "treinamentos em TI",
    "workshops técnicos",
    "mentoria em desenvolvimento",
    "consultoria estratégica",
    "planejamento tecnológico",
    "roadmap digital",
    "transformação organizacional",
    "digitalização de processos",
    "automação de rotinas",
    "workflow digital",
    "gestão documental",
    "gestão de conhecimento",
    "colaboração digital",
    "comunicação empresarial",
    "ferramentas de produtividade",
    "soluções em nuvem",
    "infraestrutura como serviço",
    "plataforma como serviço",
    "software como serviço",
    "virtualização",
    "containers",
    "kubernetes",
    "docker",
    "ansible",
    "terraform",
    "jenkins",
    "gitlab",
    "github",
    "bitbucket",
    "jira",
    "confluence",
    "slack",
    "microsoft teams",
    "zoom",
    "trello",
    "asana",
    "monday",
    "notion",
    "figma",
    "adobe xd",
    "sketch",
    "invision",
    "zeplin",
    "postman",
    "swagger",
    "graphql",
    "rest api",
    "soap",
    "webservices",
    "middleware",
    "enterprise service bus",
    "message queue",
    "event streaming",
    "kafka",
    "rabbitmq",
    "redis",
    "mongodb",
    "postgresql",
    "mysql",
    "oracle",
    "sql server",
    "nosql",
    "big data",
    "data warehouse",
    "data lake",
    "data mining",
    "business analytics",
    "data visualization",
    "power bi",
    "tableau",
    "qlik",
    "sap",
    "salesforce",
    "dynamics 365",
    "oracle erp",
    "sap erp",
    "microsoft erp",
    "sistema de gestão",
    "crm",
    "erp",
    "wms",
    "tms",
    "hrms",
    "scm",
    "plm",
    "mes",
    "cms",
    "lms",
    "ecommerce",
    "marketplace",
    "omnichannel",
    "digital marketing",
    "social media",
    "content marketing",
    "inbound marketing",
    "outbound marketing",
    "email marketing",
    "seo marketing",
    "sem marketing",
    "smm marketing",
    "analytics marketing",
    "growth hacking",
    "conversion rate",
    "landing pages",
    "sales funnel",
    "lead generation",
    "customer success",
    "customer experience",
    "user experience",
    "customer journey",
    "design system",
    "design tokens",
    "atomic design",
    "responsive design",
    "mobile first",
    "progressive enhancement",
    "graceful degradation",
    "cross browser",
    "cross platform",
    "cross device",
    "responsive images",
    "lazy loading",
    "code splitting",
    "tree shaking",
    "bundle optimization",
    "caching strategies",
    "cdn",
    "edge computing",
    "serverless",
    "lambda functions",
    "api gateway",
    "load balancing",
    "auto scaling",
    "disaster recovery",
    "high availability",
    "fault tolerance",
    "redundancy",
    "backup strategy",
    "recovery strategy",
    "business continuity",
    "incident management",
    "problem management",
    "change management",
    "release management",
    "configuration management",
    "asset management",
    "capacity management",
    "availability management",
    "service level management",
    "financial management",
    "vendor management",
    "contract management",
    "risk management",
    "security management",
    "identity management",
    "access management",
    "privilege management",
    "password management",
    "authentication",
    "authorization",
    "single sign on",
    "multi factor authentication",
    "biometric authentication",
    "encryption",
    "cryptography",
    "digital signature",
    "certificate management",
    "key management",
    "vulnerability management",
    "patch management",
    "threat intelligence",
    "security monitoring",
    "security analytics",
    "security operations",
    "incident response",
    "forensic analysis",
    "penetration testing",
    "security assessment",
    "security audit",
    "compliance audit",
    "regulatory compliance",
    "data protection",
    "privacy protection",
    "gdpr compliance",
    "lgpd compliance",
    "data governance",
    "data quality",
    "data integrity",
    "data security",
    "data privacy",
    "data retention",
    "data lifecycle",
    "data classification",
    "data catalog",
    "data lineage",
    "data masking",
    "data anonymization",
    "data pseudonymization",
    "data minimization",
    "data portability",
    "data sovereignty",
    "data residency",
    "data localization",
    "cross border data",
    "international data",
    "global data",
    "multinational data",
    "enterprise data",
    "big data analytics",
    "predictive analytics",
    "prescriptive analytics",
    "descriptive analytics",
    "diagnostic analytics",
    "real time analytics",
    "batch analytics",
    "stream analytics",
    "edge analytics",
    "fog analytics",
    "cloud analytics",
    "hybrid analytics",
    "embedded analytics",
    "self service analytics",
    "collaborative analytics",
    "social analytics",
    "mobile analytics",
    "criação de aplicativos",
  ],
  authors: [{ name: "EasyDev Soluções" }],
  creator: "EasyDev Soluções",
  publisher: "EasyDev Soluções",
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  metadataBase: new URL("https://easydevsolucoes.com.br"),
  alternates: {
    canonical: "/",
  },
  openGraph: {
    type: "website",
    locale: "pt_BR",
    url: "https://easydevsolucoes.com.br",
    title: "EasyDev - Soluções Digitais",
    description:
      "Transformando ideias em soluções digitais inovadoras. Especialistas em desenvolvimento de software e consultoria em TI.",
    siteName: "EasyDev",
    images: [
      {
        url: "/company/logoEasyDev.png",
        width: 1200,
        height: 630,
        alt: "EasyDev Logo",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "EasyDev - Soluções Digitais",
    description:
      "Transformando ideias em soluções digitais inovadoras. Especialistas em desenvolvimento de software e consultoria em TI.",
    images: ["/company/logoEasyDev.png"],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  icons: {
    icon: [
      {
        url: "/favicon/favicon.ico",
        sizes: "any",
      },
    ],
    apple: [
      {
        url: "/favicon/apple-touch-icon.png",
        sizes: "180x180",
        type: "image/png",
      },
    ],
    other: [
      {
        rel: "icon",
        type: "image/png",
        sizes: "32x32",
        url: "/favicon/favicon-32x32.png",
      },
      {
        rel: "icon",
        type: "image/png",
        sizes: "16x16",
        url: "/favicon/favicon-16x16.png",
      },
      {
        rel: "manifest",
        url: "/favicon/site.webmanifest",
      },
    ],
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <head>
        <meta
          name="google-site-verification"
          content="BPnXcpPDKavEMiXzQ94uU2dKQIVFX2pnewz4d30hu9g"
        />
        <meta name="facebook-domain-verification" content="moh7x4zv3lhhjeqhj9ck8m39i5ehn8" />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "Organization",
              name: "EasyDev Soluções",
              url: "https://easydevsolucoes.com.br",
              logo: "https://easydevsolucoes.github.io/company/logoEasyDev.png",
              description:
                "Transformando ideias em soluções digitais inovadoras. Especialistas em desenvolvimento de software e consultoria em TI.",
              address: {
                "@type": "PostalAddress",
                addressLocality: "Ibirité",
                addressRegion: "MG",
                addressCountry: "BR",
              },
              contactPoint: {
                "@type": "ContactPoint",
                telephone: "+55-31-99278-4329",
                contactType: "customer service",
                email: "contato@easydevsolucoes.com.br",
              },
              sameAs: [
                "https://www.linkedin.com/company/easydevsolucoes",
                "https://github.com/EASYDEVSolucoes",
                "https://www.instagram.com/easydevsolucoes",
              ],
            }),
          }}
        />
      </head>
      <body className={inter.className}>
        <FacebookPixel />
        <GoogleTag />
        {children}
        <WhatsAppButton />
      </body>
    </html>
  );
}
